# Data transformation

## Nupur Descripiton

Describe what you did to get/clean the data ~1/2 page.

```{r}

#Part 3 - Dataset over-view

# head(eth)
# tail(eth)
# head(btc)
# tail(btc)
# head(doge)
# tail(doge)
# 
# summary(eth)
# summary(btc)
# summary(doge)
# summary(dji_hist_prices)
# summary(sandp_hist_prices)
# 
# skim(eth)
# skim(btc)
# summary(doge)
# skim(dji_hist_prices)
# skim(sandp_hist_prices)


# No missing values in our data - as we are primarily sourcing financial data
```

Data Cleanup involved converting dates to proper datetime format to be able to display them on time series and filtering to the dates we selected, 2020 to now.

```{r}
#Part 4 - Data treatment and clean up of missing values

#4.1 - convert dates to datetime format and sort by date
eth$date <- ymd(eth$date)
btc$date <- ymd(btc$date)
doge$date <- ymd(doge$date)
dji_hist_prices$date <- ymd(dji_hist_prices$date)
sandp_hist_prices$date <- ymd(sandp_hist_prices$date)

# Twitter Data Cleanup

btc_tweet_count$Date <- dmy(btc_tweet_count$Date)
btc_tweet_count$Date <- as.Date(btc_tweet_count$Date, format ="%Y/%m/%d")
btc_tweets <- btc_tweet_count %>%
  filter(Date >= '2020-01-01', Date <= '2022-04-30') %>%
  mutate(symbol = "Bitcoin",
         TweetCount = as.double(TweetCount))

#eth
eth_tweet_count$Date <- dmy(eth_tweet_count$Date)
eth_tweet_count$Date <- as.Date(eth_tweet_count$Date, format ="%Y/%m/%d")
eth_tweets <- eth_tweet_count %>%
  filter(Date >= '2020-01-01', Date <= '2022-04-30') %>%
  mutate(symbol = "Ethereum",
         TweetCount = as.double(TweetCount))

#doge
doge_tweet_count$Date <- dmy(doge_tweet_count$Date)
doge_tweet_count$Date <- as.Date(doge_tweet_count$Date, format ="%Y/%m/%d")
doge_tweets <- doge_tweet_count %>%
  filter(Date >= '2020-01-01', Date <= '2022-04-30') %>%
  mutate(symbol = "Dogecoin",
         TweetCount = as.double(TweetCount))

```

