--- 
title: "Crypto vs Stock Market"
author: "Nupur Joshi, Fahad Alhkaja"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Every time period throughout humanity has seen radical changes, none more so than these past few decades; the typewriter was replaced by the computer, mobile phones replaced telegraphs, emails replaced physical mail, gold was replaced by an easier to transfer paper bill. Change is inevitable and that is exactly what people are claiming to do with the crypto and alternative currency market. 

Bitcoin for all intents and purposes can be thought of as a digital decentralized currency that no bank or country controls, and its popularity and price have soared throughout the past decade. Some people call it digital gold and think of it as an asset. Some people claim that it is the future and the only way we can reduce inflation and dependence on governments and institutions.

While Bitcoin is the clear front runner in terms of cryptocurrency market cap, Ethereum is the second largest.Therefore, studying Bitcoin and Ethereum can serve as a benchmark for us to understand, inform and educate us about the entire cryptocurrency market.

We can gain a deeper insight into them by studying their trends such as how they have changed over time and attempt to examine the reasons for it while comparing it to that of a more traditional market such as the US stock exchange by examining the S & P 500.

The goal of this project is to study historical price trends of Bitcoin and Ethereum amongst other features against the S & P 500 over the same time period. This study will help shed light on the relationship between these different markets people have been recently pouring their money into.



